# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/open.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(785, 294)
        Dialog.setMouseTracking(False)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.name = QtWidgets.QLabel(Dialog)
        self.name.setGeometry(QtCore.QRect(210, 40, 361, 141))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.name.setFont(font)
        self.name.setMouseTracking(True)
        self.name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name.setText("")
        self.name.setTextFormat(QtCore.Qt.PlainText)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.right = QtWidgets.QPushButton(Dialog)
        self.right.setGeometry(QtCore.QRect(600, 80, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.right.setFont(font)
        self.right.setObjectName("right")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 80, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 210, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.right.setText(_translate("Dialog", ">>>>>"))
        self.pushButton_3.setText(_translate("Dialog", "<<<<<"))
        self.pushButton.setText(_translate("Dialog", "Открыть"))
